feat(backend): close Mercury-Corporation#24
Mercury-Corporation/Crrow pull request #27
Opened 2022-12-12 11:09 UTC by ko610

2022-12-12 12:09 UTC, yuuki1293 requested changes
postの部分が動かなくなっているので変更する前に戻してください
`com.ko610.plugins.User.User`はPostリクエストをシリアライズするためのものなのでgetとpostでは共有されません。
まず、既存のものは`PostUser`等に名前を変更して衝突を回避します。
次に、Getリクエストのレスポンスのために`GetUser`クラスを作成します。返すべきデータは以下の通りです。
- name
- birthday
- sex
- introduction
- type
- coin
- nickname
- icon
- email
- school
- range
※birthdayは文字列(yyyy-mm-dd)として返します
Getリクエストでは成功した場合`HttpStatusCode.OK`(200番)が返されます

2022-12-13 12:57 UTC, yuuki1293 commented
- 変数名がuやsとなっているものをuserやsettingに変更してください（タイピングがめんどくさくて1文字にしていました。すみません。）
- `Ctrl`+`Alt`+`L`でコミット前にフォーマットしてください

2022-12-13 13:07 UTC, ko610 commented
・変数名を変更
・フォーマットの実行

2022-12-13 13:55 UTC, yuuki1293 commented
見つからなかったときは404を返すようにしてください。
要素数が0のときにsingle()を呼ぶと`NoSuchElementException`が発生します。

2022-12-14 00:08 UTC, yuuki1293 approved these changes

2022-12-14 00:08 UTC, merged